Libro.PL/Controllers/AuthorsController.cs
using AutoMapper;
using Libro.BLL.DTOs.Author;
using Libro.PL.ViewModels.Author;
namespace Libro.PL.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly IMapper _mapper;
        public AuthorsController(IAuthorService authorService, IMapper mapper)
        {
            _authorService = authorService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await _authorService.GetAllAsync();
            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var vm = _mapper.Map<IEnumerable<AuthorViewModel>>(result.Result);
            return View(vm);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Create()
        {
            return PartialView("_Form", new AuthorFormViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuthorFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState[nameof(model.Name)]?.Errors.First().ErrorMessage);

            var dto = _mapper.Map<CreateAuthorDTO>(model);
            var result = await _authorService.CreateAsync(dto);

            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var rowVm = _mapper.Map<AuthorViewModel>(result.Result);
            return PartialView("_AuthorRow", rowVm);
        }

        [HttpGet]
        [AjaxOnly]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _authorService.GetByIdAsync(id);
            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var vm = _mapper.Map<AuthorFormViewModel>(result.Result);
            return PartialView("_Form", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AuthorFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState[nameof(model.Name)]?.Errors.First().ErrorMessage);

            var dto = _mapper.Map<UpdateAuthorDTO>(model);
            var result = await _authorService.UpdateAsync(dto);

            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var rowVm = _mapper.Map<AuthorViewModel>(result.Result);
            return PartialView("_AuthorRow", rowVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ToggleStatus(int id)
        {
            var result = await _authorService.ToggleStatusAsync(id);
            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);
            var rowVm = _mapper.Map<AuthorViewModel>(result.Result);
            return Ok(rowVm?.UpdatedOn?.ToString());
        }

        public async Task<IActionResult> AllowItem(AuthorFormViewModel model)
        {
            return Json(await _authorService.IsAllowed(model.Id, model.Name));
        }
    }
}

Libro.PL/Controllers/CategoriesController.cs
using AutoMapper;
using Libro.BLL.DTOs.Category;
using Libro.PL.ViewModels.Category;


namespace Libro.PL.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public CategoriesController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAllAsync();
            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var vm = _mapper.Map<IEnumerable<CategoryViewModel>>(result.Result);
            return View(vm);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Create()
        {
            return PartialView("_Form", new CategoryFormViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState[nameof(model.Name)]?.Errors.First().ErrorMessage);

            var dto = _mapper.Map<CreateCategoryDTO>(model);
            var result = await _categoryService.CreateAsync(dto);

            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var rowVm = _mapper.Map<CategoryViewModel>(result.Result);
            return PartialView("_CategoryRow", rowVm);
        }

        [HttpGet]
        [AjaxOnly]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _categoryService.GetByIdAsync(id);
            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var vm = _mapper.Map<CategoryFormViewModel>(result.Result);
            return PartialView("_Form", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState[nameof(model.Name)]?.Errors.First().ErrorMessage);

            var dto = _mapper.Map<UpdateCategoryDTO>(model);
            var result = await _categoryService.UpdateAsync(dto);

            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var rowVm = _mapper.Map<CategoryViewModel>(result.Result);
            return PartialView("_CategoryRow", rowVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ToggleStatus(int id)
        {
            var result = await _categoryService.ToggleStatusAsync(id);
            if (result.HasErrorMessage)
                return StatusCode((int)result.StatusCode, result.ErrorMessage);

            var rowVm = _mapper.Map<CategoryViewModel>(result.Result);
            return Ok(rowVm?.UpdatedOn?.ToString());
        }

        public async Task<IActionResult> AllowItem(CategoryFormViewModel model)
        {
            return Json(await _categoryService.IsAllowed(model.Id, model.Name));
        }
    }
}

Libro.PL/Views/Shared/_Aside.cshtml
<!--begin::Aside-->
<div id="kt_aside" class="aside card" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_toggle">
	<!--begin::Aside menu-->
	<div class="aside-menu flex-column-fluid px-4">
		<!--begin::Aside Menu-->
		<div class="hover-scroll-overlay-y my-5 pe-4 me-n4" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="{default: '#kt_aside_footer', lg: '#kt_header, #kt_aside_footer'}" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="{default: '5px', lg: '75px'}">
			<!--begin::Menu-->
			<div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6" id="#kt_aside_menu" data-kt-menu="true">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" asp-controller="Home" asp-action="Index" active-when="Home">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M11 2.375L2 9.575V20.575C2 21.175 2.4 21.575 3 21.575H9C9.6 21.575 10 21.175 10 20.575V14.575C10 13.975 10.4 13.575 11 13.575H13C13.6 13.575 14 13.975 14 14.575V20.575C14 21.175 14.4 21.575 15 21.575H21C21.6 21.575 22 21.175 22 20.575V9.575L13 2.375C12.4 1.875 11.6 1.875 11 2.375Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Home</span>
					</a>
					<!--end:Menu link-->
					<!--begin:Menu link-->
					<a class="menu-link" asp-controller="Categories" asp-action="Index" active-when="Categories">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path opacity="0.3" d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z" fill="currentColor" />
									<path d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Categories</span>
					</a>
					<!--end:Menu link-->
					<!--begin:Menu link-->
					<a class="menu-link" asp-controller="Authors" asp-action="Index" active-when="Authors">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path opacity="0.3" d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z" fill="currentColor" />
									<path d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Authors</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
			</div>
			<!--end::Menu-->
		</div>
	</div>
	<!--end::Aside menu-->
</div>
<!--end::Aside-->